# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [
          16
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build mod
        run: ./gradlew build
      - name: Capture build artifacts
        if: ${{ matrix.java == '16' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
